// Array of button colors
var buttonColours = ["red", "blue", "green", "yellow"];
var gamePattern = []; // Sequence of colors generated by the game
var userClickedPattern = []; // Sequence clicked by the user
var started = false; // Tracks if the game has started
var level = 0; // Current game level

// Start the game on key press
$(document).keydown(function () {
    if (!started) {
        $("#level-title").text("Level " + level);
        nextSequence();
        started = true;
    }
});

// Detect button click and handle user input
$(".btn").click(function () {
    var userChosenColour = $(this).attr("id");
    userClickedPattern.push(userChosenColour);

    playSound(userChosenColour); // Play sound for the clicked button
    animatePress(userChosenColour); // Add button press animation

    checkSelectedPattern(userClickedPattern.length - 1); // Check user's input
});

// Check the user's sequence against the game pattern
function checkSelectedPattern(currentIndex) {
    if (gamePattern[currentIndex] === userClickedPattern[currentIndex]) {
        // Check if the user has completed the sequence
        if (userClickedPattern.length === gamePattern.length) {
            setTimeout(function () {
                nextSequence(); // Generate the next sequence
            }, 1000);
        }
    } else {
        // Handle incorrect input
        playSound("wrong");
        $("body").addClass("game-over");
        $("#level-title").text("Game Over, Press Any Key to Restart");
        setTimeout(() => {
            $("Body").removeClass("game-over");
        }, 200);
        gameOver(); // Reset the game
    }
}

// Reset game variables
function gameOver() {
    level = 0;
    gamePattern = [];
    started = false;
}

// Generate the next sequence and update the game level
function nextSequence() {
    userClickedPattern = [];
    level++;
    $("#level-title").text("Level " + level);

    var randomNumber = Math.floor(Math.random() * 4); // Random index for colors
    var randomChosenColour = buttonColours[randomNumber];
    gamePattern.push(randomChosenColour);

    // Flash the selected button
    $("#" + randomChosenColour)
        .fadeOut(100)
        .fadeIn(100);
    playSound(randomChosenColour); // Play corresponding sound
}

// Play sound for a given color
function playSound(name) {
    var audio = new Audio("./sounds/" + name + ".mp3");
    audio.play();
}

// Add animation for a button press
function animatePress(currentColour) {
    $("#" + currentColour).addClass("pressed");
    setTimeout(() => {
        $("#" + currentColour).removeClass("pressed");
    }, 100);
}